# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputFolder = QtWidgets.QLineEdit(self.widget_2)
        self.inputFolder.setObjectName("inputFolder")
        self.horizontalLayout.addWidget(self.inputFolder)
        self.buttonFolder = QtWidgets.QPushButton(self.widget_2)
        self.buttonFolder.setObjectName("buttonFolder")
        self.horizontalLayout.addWidget(self.buttonFolder)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.buttonData = QtWidgets.QPushButton(self.widget)
        self.buttonData.setObjectName("buttonData")
        self.verticalLayout_2.addWidget(self.buttonData)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignTop)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line = QtWidgets.QFrame(self.widget_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonShowData = QtWidgets.QPushButton(self.widget_4)
        self.buttonShowData.setObjectName("buttonShowData")
        self.horizontalLayout_2.addWidget(self.buttonShowData)
        self.buttonShowStat = QtWidgets.QPushButton(self.widget_4)
        self.buttonShowStat.setObjectName("buttonShowStat")
        self.horizontalLayout_2.addWidget(self.buttonShowStat)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.dataOutput = QtWidgets.QTextEdit(self.widget_3)
        self.dataOutput.setStyleSheet("border: 1px solid;")
        self.dataOutput.setReadOnly(True)
        self.dataOutput.setObjectName("dataOutput")
        self.verticalLayout_3.addWidget(self.dataOutput)
        self.verticalLayout.addWidget(self.widget_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Chemin du fichier d'entrée"))
        self.buttonFolder.setText(_translate("MainWindow", "..."))
        self.buttonData.setText(_translate("MainWindow", "Récupérer les données"))
        self.buttonShowData.setText(_translate("MainWindow", "Voir les données"))
        self.buttonShowStat.setText(_translate("MainWindow", "Voir les stats"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
