name: Ruff
on: 
    push:
        branches:
        - main
    pull_request:

env:
    FORCE_COLOR: 1

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Install uv
        uses: yezz123/setup-uv@v4
        with:
          uv-venv: venv

      - name: Activate virtualenv
        run: |
            . venv/bin/activate
            echo PATH=$PATH >> $GITHUB_ENV

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Check Lint
        run: ruff check 

      - name: Check format
        run: ruff format --check
