name: Ruff
on: 
    push:
        branches:
        - main
    pull_request:

env:
    FORCE_COLOR: 1

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Install dependencies
        run: uv pip install --system -r requirements.txt

      - name: Check Lint
        run: ruff check 

      - name: Check format
        run: ruff format --check

      - name: Run tests
        run: pytest
